Repository romi/plant-3d-explorer, pull requests merged in 2021-03, with the labels that each got.

#102 Update the package to match new name: plant 3d explorer
  README.md
  doc/architecture.mdx
  doc/fetchingData.mdx
  doc/index.mdx
  doc/redux.mdx
  doc/tests.mdx
  docker/Dockerfile
Labels: cleanup, documentation

#104 Fix broken docker
  README.md
  doc/images/screenshot_1.png
  doc/images/screenshot_2.png
  docker/Dockerfile
  docker/build.sh
  docker/docker-compose.yml
  docker/run.sh
Labels: bug

#107 Rename : Change reference to old romidata name
  README.md
  docker/docker-compose.yml
  src/flow/scans/accessors.js
Labels: refactoring
